In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('./weatherAUS.csv')
df=df.set_index("Date")

In [3]:
df

Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
Date                                                                     
2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   
...             ...      ...      ...       ...          ...       ...   
2017-06-21    Uluru      2.8     23.4       0.0          NaN       NaN   
2017-06-22    Uluru      3.6     25.3       0.0          NaN       NaN   
2017-06-23    Uluru      5.4     26.9       0.0          NaN       NaN   
2017-06-24    Uluru      7.8     27.0       0.0          NaN       NaN   
2017-06-25    Uluru     14.9      NaN       0.0          NaN       NaN   

           WindGustDir  WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  \
Date                                                         ...                
2008-12-01           W           44.0          W        WNW  ...         71.0   
2008-12-02         WNW           44.0        NNW        WSW  ...         44.0   
2008-12-03         WSW           46.0          W        WSW  ...         38.0   
2008-12-04          NE           24.0         SE          E  ...         45.0   
2008-12-05           W           41.0        ENE         NW  ...         82.0   
...                ...            ...        ...        ...  ...          ...   
2017-06-21           E           31.0         SE        ENE  ...         51.0   
2017-06-22         NNW           22.0         SE          N  ...         56.0   
2017-06-23           N           37.0         SE        WNW  ...         53.0   
2017-06-24          SE           28.0        SSE          N  ...         51.0   
2017-06-25         NaN            NaN        ESE        ESE  ...         62.0   

            Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  \
Date                                                                    
2008-12-01         22.0       1007.7       1007.1       8.0       NaN   
2008-12-02         25.0       1010.6       1007.8       NaN       NaN   
2008-12-03         30.0       1007.6       1008.7       NaN       2.0   
2008-12-04         16.0       1017.6       1012.8       NaN       NaN   
2008-12-05         33.0       1010.8       1006.0       7.0       8.0   
...                 ...          ...          ...       ...       ...   
2017-06-21         24.0       1024.6       1020.3       NaN       NaN   
2017-06-22         21.0       1023.5       1019.1       NaN       NaN   
2017-06-23         24.0       1021.0       1016.8       NaN       NaN   
2017-06-24         24.0       1019.4       1016.5       3.0       2.0   
2017-06-25         36.0       1020.2       1017.9       8.0       8.0   

            Temp9am  Temp3pm  RainToday  RainTomorrow  
Date                                                   
2008-12-01     16.9     21.8         No            No  
2008-12-02     17.2     24.3         No            No  
2008-12-03     21.0     23.2         No            No  
2008-12-04     18.1     26.5         No            No  
2008-12-05     17.8     29.7         No            No  
...             ...      ...        ...           ...  
2017-06-21     10.1     22.4         No            No  
2017-06-22     10.9     24.5         No            No  
2017-06-23     12.5     26.1         No            No  
2017-06-24     15.1     26.0         No            No  
2017-06-25     15.0     20.9         No           NaN  

[145460 rows x 22 columns]

In [4]:
# from sklearn.preprocessing import StandardScaler
# encoder=StandardScaler()
# encoder.fit(df)
# encoder=encoder.transform(df)
# df_frame=pd.DataFrame(encoder,columns=df.columns)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 145460 entries, 2008-12-01 to 2017-06-25
Data columns (total 22 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   Location       145460 non-null  object 
 1   MinTemp        143975 non-null  float64
 2   MaxTemp        144199 non-null  float64
 3   Rainfall       142199 non-null  float64
 4   Evaporation    82670 non-null   float64
 5   Sunshine       75625 non-null   float64
 6   WindGustDir    135134 non-null  object 
 7   WindGustSpeed  135197 non-null  float64
 8   WindDir9am     134894 non-null  object 
 9   WindDir3pm     141232 non-null  object 
 10  WindSpeed9am   143693 non-null  float64
 11  WindSpeed3pm   142398 non-null  float64
 12  Humidity9am    142806 non-null  float64
 13  Humidity3pm    140953 non-null  float64
 14  Pressure9am    130395 non-null  float64
 15  Pressure3pm    130432 non-null  float64
 16  Cloud9am       89572 non-null   float64
 17  Cloud3pm       86102 

In [6]:
df.head

<bound method NDFrame.head of            Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
Date                                                                     
2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   
...             ...      ...      ...       ...          ...       ...   
2017-06-21    Uluru      2.8     23.4       0.0          NaN       NaN   
2017-06-22    Uluru      3.6     25.3       0.0          NaN       NaN   
2017-06-23    Uluru      5.4     26.9       0.0          NaN       NaN   
2017-06-24    Uluru      7.8     27.0       0.0          NaN       NaN   
2017-06-25    Uluru     14.9      NaN       0.0          NaN       NaN   

       

In [7]:
df["Location"].unique()

array(['Albury', 'BadgerysCreek', 'Cobar', 'CoffsHarbour', 'Moree',
       'Newcastle', 'NorahHead', 'NorfolkIsland', 'Penrith', 'Richmond',
       'Sydney', 'SydneyAirport', 'WaggaWagga', 'Williamtown',
       'Wollongong', 'Canberra', 'Tuggeranong', 'MountGinini', 'Ballarat',
       'Bendigo', 'Sale', 'MelbourneAirport', 'Melbourne', 'Mildura',
       'Nhil', 'Portland', 'Watsonia', 'Dartmoor', 'Brisbane', 'Cairns',
       'GoldCoast', 'Townsville', 'Adelaide', 'MountGambier', 'Nuriootpa',
       'Woomera', 'Albany', 'Witchcliffe', 'PearceRAAF', 'PerthAirport',
       'Perth', 'SalmonGums', 'Walpole', 'Hobart', 'Launceston',
       'AliceSprings', 'Darwin', 'Katherine', 'Uluru'], dtype=object)

In [8]:
df["MinTemp"].unique()

array([13.4,  7.4, 12.9,  9.2, 17.5, 14.6, 14.3,  7.7,  9.7, 13.1, 15.9,
       12.6,  8.4,  9.8, 14.1, 13.5, 11.2, 11.5, 17.1, 20.5, 15.3, 16.2,
       16.9, 20.1, 19.7, 12.5, 12. , 11.3,  9.6, 10.5, 12.3, 13.7, 16.1,
       14. , 17. , 17.3, 17.2, 17.4, 19.8, 14.9, 13.9, 18.6, 19.3, 24.4,
       18.8, 20.8, 15.7, 18.5, 20.4, 21.8, 22.3, 22. , 28. , 21.5, 21.7,
       23.5, 28.3, 18.4, 12.4, 13.3, 18. , 18.7, 15.5,  8.9, 15. , 15.4,
       16. , 12.8, 13.2, 13.8,  7.6,  8.3, 11. , 20.9, 16.4, 10. ,  8.8,
        9.3, 14.4, 10.8, 10.1,  9.1, 10.4, 12.2, 10.7,  7.8,  8.1,  7.5,
        8.2, 11.6, 13. ,  9.9,  3.5,  6.6,  7. ,  5.7,  6.2,  6. , 10.6,
        8.6,  4.5,  5.4,  2.1,  1.8,  7.2,  4.6,  4.2,  5.2,  4.1,  3.2,
        4.3,  3.7,  3.6,  6.9, 10.3,  3. ,  2.6,  5.1,  4.4,  4.7,  6.7,
        8. ,  2.2,  1.7,  2.8,  9. ,  6.3, -2. , -1.3,  2. ,  0.5,  1.2,
        0.6,  0.9,  5. ,  3.9,  3.4,  0. , -1.5, -1.7, -0.4,  0.1,  4.8,
        5.9,  2.9, -0.6, -0.3, -1. ,  0.8, -0.1,  1

In [9]:
df["MaxTemp"].unique()

array([22.9, 25.1, 25.7, 28. , 32.3, 29.7, 25. , 26.7, 31.9, 30.1, 30.4,
       21.7, 18.6, 21. , 24.6, 27.7, 20.9, 22.5, 25.6, 29.3, 33. , 31.8,
       30.9, 32.4, 33.9, 32.7, 27.2, 24.2, 24.4, 26.5, 23.9, 28.8, 34.6,
       35.8, 37.9, 38.9, 28.3, 28.4, 30.8, 32. , 34.7, 37.7, 43. , 32.2,
       36.6, 39.9, 38.1, 34. , 35.2, 30.6, 34.3, 38.4, 38.2, 40.7, 41.5,
       42.9, 42.7, 43.1, 38.3, 36.9, 41.2, 42.2, 44.8, 40.2, 31.2, 27.3,
       21.6, 29. , 29.2, 31.3, 31.1, 29.1, 31.7, 33.2, 29.6, 32.6, 34.5,
       30.3, 22.1, 22. , 24. , 27.9, 30.2, 30.5, 25.8, 27. , 19.7, 21.9,
       25.3, 33.5, 33.6, 30. , 31.6, 22.3, 29.8, 27.6, 28.9, 29.9, 32.1,
       28.1, 21.4, 24.9, 25.4, 20. , 23.4, 22.7, 16.2, 15.8, 12.9, 11.5,
       14.5, 12.2, 16.5, 17. , 19.2, 18.9, 19.1, 18.8, 19.3, 18.4, 19. ,
       20.5, 19.5, 17.7, 18.5, 15.1, 16.3, 16.6, 16.4, 15.6, 19.8, 21.1,
       20.3, 18.1, 15.7, 16.8, 17.1, 14.3, 13.4, 17.4, 16.1, 10.5, 11.6,
       12. ,  8.8,  9.6,  8.2, 12.4, 14.9, 15.9, 14

In [10]:
df["Rainfall"].unique()

array([6.000e-01, 0.000e+00, 1.000e+00, 2.000e-01, 1.400e+00, 2.200e+00,
       1.560e+01, 3.600e+00,       nan, 1.680e+01, 1.060e+01, 1.200e+00,
       8.000e-01, 6.400e+00, 4.000e-01, 3.000e+00, 5.800e+00, 1.160e+01,
       1.800e+00, 8.600e+00, 1.260e+01, 8.400e+00, 6.200e+00, 2.000e+01,
       2.100e+01, 3.200e+00, 4.800e+00, 4.200e+00, 8.000e+00, 1.440e+01,
       4.600e+00, 2.000e+00, 5.600e+00, 1.600e+00, 6.000e+00, 4.400e+00,
       5.400e+00, 5.000e+00, 7.800e+00, 6.800e+00, 9.800e+00, 3.800e+00,
       2.400e+00, 5.200e+00, 6.600e+00, 1.340e+01, 1.020e+01, 2.880e+01,
       7.000e+00, 2.580e+01, 9.400e+00, 1.240e+01, 5.220e+01, 2.060e+01,
       6.600e+01, 1.100e+01, 1.700e+01, 1.040e+01, 2.800e+01, 2.140e+01,
       1.860e+01, 7.200e+00, 8.200e+00, 1.080e+01, 1.540e+01, 9.600e+00,
       4.000e+00, 2.180e+01, 2.080e+01, 2.480e+01, 1.000e+01, 1.140e+01,
       1.900e+01, 2.220e+01, 3.280e+01, 3.400e+00, 5.080e+01, 5.260e+01,
       1.920e+01, 1.880e+01, 1.480e+01, 1.200e+01, 

In [11]:
df["Evaporation"].unique()

array([     nan, 1.20e+01, 1.48e+01, 1.26e+01, 1.08e+01, 1.14e+01,
       1.12e+01, 1.30e+01, 9.80e+00, 1.46e+01, 1.10e+01, 1.28e+01,
       1.38e+01, 1.64e+01, 1.74e+01, 1.60e+01, 1.36e+01, 8.00e+00,
       8.20e+00, 8.60e+00, 1.42e+01, 1.58e+01, 1.62e+01, 1.34e+01,
       1.44e+01, 1.18e+01, 1.56e+01, 1.52e+01, 1.16e+01, 9.60e+00,
       6.60e+00, 6.00e-01, 6.00e+00, 3.00e+00, 2.00e+00, 5.20e+00,
       9.00e+00, 1.02e+01, 1.00e+01, 7.40e+00, 8.40e+00, 9.20e+00,
       9.40e+00, 1.24e+01, 1.04e+01, 7.20e+00, 6.80e+00, 7.60e+00,
       4.40e+00, 6.40e+00, 7.80e+00, 7.00e+00, 8.80e+00, 6.20e+00,
       5.80e+00, 2.00e-01, 2.40e+00, 1.80e+00, 2.20e+00, 2.80e+00,
       5.00e+00, 5.60e+00, 4.80e+00, 4.20e+00, 4.00e+00, 3.20e+00,
       4.60e+00, 3.40e+00, 3.60e+00, 0.00e+00, 1.40e+00, 3.80e+00,
       8.00e-01, 2.60e+00, 1.60e+00, 1.20e+00, 1.00e+00, 5.40e+00,
       1.06e+01, 1.68e+01, 1.70e+01, 2.02e+01, 1.40e+01, 1.72e+01,
       1.22e+01, 1.50e+01, 1.82e+01, 1.32e+01, 4.10e+00, 1.70e

In [12]:
df["Sunshine"].unique()

array([ nan, 12.3, 13. , 13.3, 10.6, 12.2,  8.4,  0. , 12.6, 13.2, 12.7,
       12.1, 10.3, 13.1, 12.9, 11.3,  6.9, 10.9,  3.7,  5.9, 10.5, 12.4,
       13.4, 13.6,  7.4, 10. ,  2.3,  6.6,  0.3, 10.7, 11.6, 10.2,  9. ,
       12. ,  3. ,  7.9, 11.5, 11.2,  4.8,  5.8,  6. , 11.1, 11.8, 11.4,
       10.8,  7.8, 11. ,  5.5,  4.7,  4.2,  4.4,  6.2,  9.8,  9.9,  4.3,
        8. ,  9.6, 10.4,  9.3,  8.7,  7.6,  7.5, 10.1,  6.3,  2.8,  0.7,
        9.4,  9.7,  0.6,  5.1,  8.3,  4.1,  3.9,  6.8,  8.6,  2.7,  8.2,
        3.1,  1.8,  0.1,  0.8,  3.4,  7.1,  5. ,  5.7,  6.1,  7. ,  2.9,
        2.5,  4.6,  8.9,  9.1,  1.7,  8.1,  9.5,  1.2,  1.4,  8.8,  2.2,
        3.5,  9.2,  1.9, 11.7, 11.9,  7.7,  0.9, 12.5,  2.1, 12.8, 13.7,
        8.5,  0.2,  4. ,  2.4,  5.2,  0.5,  6.4,  4.5,  1.1,  2. ,  0.4,
        1.5,  3.3,  6.5,  2.6,  3.8,  3.6,  3.2,  6.7,  5.4,  7.2,  4.9,
        1. ,  1.6,  5.3,  7.3,  5.6,  1.3, 13.8, 13.5, 14. , 13.9, 14.1,
       14.5, 14.3, 14.2])

In [13]:
df["WindGustDir"].unique()

array(['W', 'WNW', 'WSW', 'NE', 'NNW', 'N', 'NNE', 'SW', nan, 'ENE',
       'SSE', 'S', 'NW', 'SE', 'ESE', 'E', 'SSW'], dtype=object)

In [14]:
df["WindGustSpeed"].unique()

array([ 44.,  46.,  24.,  41.,  56.,  50.,  35.,  80.,  28.,  30.,  31.,
        61.,  nan,  22.,  63.,  43.,  26.,  33.,  57.,  48.,  39.,  37.,
        52.,  98.,  54.,  83.,  59.,  70.,  69.,  17.,  20.,  19.,  15.,
        13.,  11.,  72.,  85.,  65.,  78., 107.,  74.,  67.,  94.,  76.,
        81.,  87.,   9.,   7.,  89.,  91.,  93., 102., 100., 113., 117.,
        96., 111., 106., 135., 104., 120., 115., 126., 109., 122., 124.,
       130.,   6.])

In [15]:
df["WindDir9am"].unique()

array(['W', 'NNW', 'SE', 'ENE', 'SW', 'SSE', 'S', 'NE', nan, 'SSW', 'N',
       'WSW', 'ESE', 'E', 'NW', 'WNW', 'NNE'], dtype=object)

In [16]:
df["WindDir3pm"].unique()

array(['WNW', 'WSW', 'E', 'NW', 'W', 'SSE', 'ESE', 'ENE', 'NNW', 'SSW',
       'SW', 'SE', 'N', 'S', 'NNE', nan, 'NE'], dtype=object)

In [17]:
df["WindSpeed9am"].unique()

array([ 20.,   4.,  19.,  11.,   7.,   6.,  15.,  17.,  28.,  24.,  nan,
         9.,   0.,  13.,   2.,  26.,  30.,  22.,  35.,  37.,  31.,  33.,
        48.,  39.,  44.,  43.,  41.,  46.,  56.,  83.,  74.,  52.,  65.,
        50., 130.,  54.,  61.,  57.,  59.,  87.,  67.,  63.,  69.,  72.])

In [18]:
df["WindSpeed3pm"].unique()

array([24., 22., 26.,  9., 20., 17., 28., 11.,  6., 13., 30., 19., 31.,
        7., 15., 48.,  4., 33.,  0.,  2., nan, 37., 46., 39., 50., 35.,
       44., 41., 43., 56., 61., 54., 52., 83., 65., 78., 57., 63., 59.,
       74., 72., 69., 76., 87., 67.])

In [19]:
df["Humidity9am"].unique()

array([ 71.,  44.,  38.,  45.,  82.,  55.,  49.,  48.,  42.,  58.,  89.,
        76.,  65.,  57.,  50.,  69.,  80.,  47.,  56.,  54.,  41.,  78.,
        46.,  43.,  33.,  34.,  36.,  52.,  51.,  40.,  35.,  39.,  60.,
        37.,  27.,  32.,  53.,  20.,  66.,  63.,  62.,  87.,  61.,  59.,
        92.,  72.,  67.,  75.,  88.,  68.,  73.,  74.,  83.,  77.,  70.,
        81.,  86.,  97.,  99.,  91.,  85.,  93.,  84.,  94.,  79.,  98.,
        96.,  95.,  90.,  64.,  29.,  21., 100.,  nan,  24.,  25.,  31.,
        18.,  23.,  26.,  28.,  30.,  19.,  22.,  17.,  15.,   9.,  12.,
        13.,  16.,   6.,  10.,  14.,  11.,   7.,   8.,   5.,   3.,   2.,
         4.,   0.,   1.])

In [20]:
df["Humidity3pm"].unique()

array([ 22.,  25.,  30.,  16.,  33.,  23.,  19.,   9.,  27.,  91.,  93.,
        43.,  32.,  28.,  82.,  65.,  26.,  24.,  17.,  15.,  70.,  12.,
         8.,  31.,  20.,  10.,  21.,  39.,  13.,  11.,  69.,  18.,  14.,
        35.,  90.,  68.,  74.,  41.,  34.,  78.,  49.,  37.,  42.,  47.,
        52.,  29.,  86.,  89.,  62.,  79.,  48.,  46.,  38.,  44.,  51.,
        36.,  45.,  40.,  53.,  61.,  59.,  63.,  54.,  57.,  50.,  58.,
        75.,  97.,  80.,  95.,  56.,  72.,  60.,  71.,  73.,  81.,  76.,
        64.,  87.,  85.,  67.,  55.,  77.,  84.,   7.,  99.,  92.,  66.,
        83.,  94.,  96.,  88.,  nan, 100.,  98.,   5.,   6.,   1.,   4.,
         2.,   3.,   0.])

In [21]:
df["Pressure9am"].unique()

array([1007.7, 1010.6, 1007.6, 1017.6, 1010.8, 1009.2, 1009.6, 1013.4,
       1008.9, 1007. , 1011.8, 1010.5,  994.3, 1001.2, 1009.7, 1012.2,
       1005.8, 1009.4, 1019.2, 1019.3, 1013.6, 1007.8, 1011. , 1012.9,
       1010.9, 1006.8, 1005.2, 1004.8, 1005.6, 1006.1, 1004.5, 1014.4,
       1018.7, 1015.1, 1012.6, 1011.9, 1017.8, 1009.9, 1014.1, 1015.7,
       1011.6, 1008.4, 1019.7, 1015.8, 1010.1, 1005.3, 1007.9, 1005.4,
       1016.5, 1017.7, 1014.9, 1014.6, 1014.2, 1012.5, 1011.7, 1008.8,
       1005.9, 1008. , 1008.2, 1009.3, 1012.8, 1017. , 1023.3, 1022.5,
       1016.2, 1017.2, 1012.4, 1015.6, 1013. , 1014. , 1016.6, 1007.5,
       1014.7, 1014.5, 1013.7, 1015.2, 1019.5, 1021.3, 1017.4, 1012.7,
       1013.3, 1016.3, 1014.8, 1019.1, 1023. , 1023.8, 1022.4, 1023.2,
       1022.6, 1018.8, 1019.8, 1020.4, 1021.8, 1026.7, 1027.1, 1024.2,
       1021.5, 1024.4, 1024.1, 1018.5, 1022.8, 1022.7, 1023.6, 1025.2,
       1026. , 1004. , 1013.8, 1018. , 1023.1, 1023.4, 1026.9, 1028.7,
      

In [22]:
df["Pressure3pm"].unique()

array([1007.1  , 1007.8  , 1008.7  , 1012.8  , 1006.   , 1005.4  ,
       1008.2  , 1010.1  , 1003.6  , 1005.7  , 1004.2  ,  993.   ,
       1001.8  , 1010.3  , 1010.4  , 1002.2  , 1009.7  , 1017.1  ,
       1014.8  , 1008.1  , 1007.6  , 1001.7  , 1003.4  , 1005.1  ,
       1003.2  , 1013.1  , 1009.2  , 1006.7  , 1002.7  , 1010.9  ,
       1013.7  , 1006.8  , 1012.1  , 1006.9  , 1012.7  , 1017.4  ,
       1016.2  , 1010.6  , 1004.8  , 1005.9  ,  997.8  , 1003.9  ,
       1014.6  , 1014.1  , 1011.6  , 1011.8  , 1010.2  , 1010.5  ,
       1007.4  , 1004.7  , 1002.6  , 1005.   , 1003.8  , 1006.5  ,
       1008.5  , 1011.1  , 1017.3  , 1019.7  , 1016.4  , 1013.8  ,
       1013.5  , 1007.5  , 1004.5  , 1010.8  , 1012.4  , 1013.4  ,
       1015.   , 1012.6  , 1004.6  , 1009.   , 1012.   , 1014.7  ,
       1015.9  , 1018.   , 1018.9  , 1008.   , 1013.2  , 1013.9  ,
       1013.6  , 1014.4  , 1019.2  , 1017.2  , 1020.7  , 1020.6  ,
       1019.1  , 1019.5  , 1019.4  , 1018.4  , 1012.9  , 1019.

In [23]:
df["Cloud9am"].unique()

array([ 8., nan,  7.,  1.,  0.,  5.,  4.,  2.,  6.,  3.,  9.])

In [24]:
df["Cloud3pm"].unique()

array([nan,  2.,  8.,  7.,  1.,  5.,  4.,  6.,  3.,  0.,  9.])

In [25]:
df["Temp9am"].unique()

array([16.9, 17.2, 21. , 18.1, 17.8, 20.6, 16.3, 18.3, 20.1, 20.4, 15.9,
       17.4, 15.8, 17.3, 18. , 15.5, 19.1, 24.5, 23.8, 20.9, 21.5, 23.2,
       26.6, 24.6, 21.6, 12.5, 19.7, 14.9, 17.1, 20.7, 22.4, 23.1, 25.2,
       17.9, 20.2, 22.8, 24.2, 24.3, 25.6, 27.6, 16. , 22. , 26.8, 27.3,
       26.1, 23.3, 21.2, 23.4, 25.8, 28.2, 29. , 29.2, 29.9, 32.4, 28.8,
       27.2, 25.5, 26.5, 28.7, 29.6, 34.5, 18.7, 16.7, 17. , 19.2, 21.4,
       22.1, 19.3, 15. , 20. , 22.2, 23. , 15.6, 13.9, 12.6, 13.3, 17.6,
       18.6, 19. , 19.9, 12.7, 12.2, 12.1, 14.7, 18.8, 15.4, 16.2, 16.5,
       14. , 16.6, 18.4, 12.9, 13.8, 15.1, 16.4, 16.1, 20.5,  9.6, 12.4,
       14.1, 11.2,  9.5,  7.6, 10.1,  8.2,  7.9,  7.2, 10.6, 10.3, 10. ,
        8.3, 11. ,  9.4, 11.7,  8.5,  9.1,  7.5, 13. ,  7. ,  8.8,  7.4,
       11.9, 11.6, 13.6,  7.1, 10.2,  8. ,  9.2, 11.3,  4.7,  6.8,  4.9,
        2.2,  1.9,  5.9,  6.5,  5.4,  6.6,  5.6,  6.9,  8.4,  9.8, 13.5,
        7.8,  2.3,  2.4,  3.3,  3.8,  4.8,  8.1,  9

In [26]:
df["Temp3pm"].unique()

array([21.8, 24.3, 23.2, 26.5, 29.7, 28.9, 24.6, 25.5, 30.2, 28.2, 28.8,
       17. , 15.8, 19.8, 23.5, 26.2, 18.1, 21.5, 21. , 27.3, 31.6, 30.8,
       29. , 31.2, 33. , 32.1, 26.1, 18.2, 22.7, 25.7, 22.1, 33.9, 34.4,
       36.8, 38.4, 27.6, 26.6, 29.3, 30. , 33.2, 35.7, 41.5, 27.1, 25.8,
       30.5, 37.7, 36.1, 33.1, 36.5, 36.2, 39.2, 40.1, 41.2, 42. , 41.9,
       37.1, 35.2, 39.7, 41.6, 43.4, 38.5, 29.4, 24.9, 17.3, 28.5, 29.2,
       29.5, 27. , 30.7, 32.7, 26.8, 29.8, 31.3, 33.4, 28.6, 33.6, 28.1,
       21.9, 21.4, 22. , 29.6, 18.8, 23.8, 19.7, 18.3, 20.5, 23.9, 27.2,
       32.6, 33.5, 31.4, 19.6, 27.7, 29.9, 30.9, 27.4, 20.3, 21.2, 20.9,
       21.6, 25. , 24.4, 23.1, 18.9, 19.4, 22.9, 23.6, 21.3, 22.3, 22.6,
       15.1, 14.5, 11.6,  9.4, 14. , 12.1, 16.1, 16.3, 19.1, 18.5, 18.4,
       19.2, 20.2, 17.7, 18. , 14.6, 15.3, 15.9, 14.7, 18.7, 21.7, 20.8,
       19.5, 17.4, 15.6, 16.7, 16.8, 13.4, 13. , 16.5, 10.2, 11.5, 11.4,
        7.9,  9.7,  8.8, 15.5, 13.9, 15.4, 14.9, 16

In [27]:
df["RainToday"].unique()

array(['No', 'Yes', nan], dtype=object)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 145460 entries, 2008-12-01 to 2017-06-25
Data columns (total 22 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   Location       145460 non-null  object 
 1   MinTemp        143975 non-null  float64
 2   MaxTemp        144199 non-null  float64
 3   Rainfall       142199 non-null  float64
 4   Evaporation    82670 non-null   float64
 5   Sunshine       75625 non-null   float64
 6   WindGustDir    135134 non-null  object 
 7   WindGustSpeed  135197 non-null  float64
 8   WindDir9am     134894 non-null  object 
 9   WindDir3pm     141232 non-null  object 
 10  WindSpeed9am   143693 non-null  float64
 11  WindSpeed3pm   142398 non-null  float64
 12  Humidity9am    142806 non-null  float64
 13  Humidity3pm    140953 non-null  float64
 14  Pressure9am    130395 non-null  float64
 15  Pressure3pm    130432 non-null  float64
 16  Cloud9am       89572 non-null   float64
 17  Cloud3pm       86102 

In [29]:
df["Location"].unique()

array(['Albury', 'BadgerysCreek', 'Cobar', 'CoffsHarbour', 'Moree',
       'Newcastle', 'NorahHead', 'NorfolkIsland', 'Penrith', 'Richmond',
       'Sydney', 'SydneyAirport', 'WaggaWagga', 'Williamtown',
       'Wollongong', 'Canberra', 'Tuggeranong', 'MountGinini', 'Ballarat',
       'Bendigo', 'Sale', 'MelbourneAirport', 'Melbourne', 'Mildura',
       'Nhil', 'Portland', 'Watsonia', 'Dartmoor', 'Brisbane', 'Cairns',
       'GoldCoast', 'Townsville', 'Adelaide', 'MountGambier', 'Nuriootpa',
       'Woomera', 'Albany', 'Witchcliffe', 'PearceRAAF', 'PerthAirport',
       'Perth', 'SalmonGums', 'Walpole', 'Hobart', 'Launceston',
       'AliceSprings', 'Darwin', 'Katherine', 'Uluru'], dtype=object)

In [30]:
MinTemp_min=df["MinTemp"].min()
MinTemp_max=df["MinTemp"].max()

In [31]:
MaxTemp_min=df["MaxTemp"].min()
MaxTemp_max=df["MaxTemp"].max()

In [32]:
Rainfall_min=df["Rainfall"].min()
Rainfall_max=df["Rainfall"].max()

In [33]:
Evaporation_min=df["Evaporation"].min()
Evaporation_max=df["Evaporation"].max()

In [34]:
Sunshine_min=df["Sunshine"].min()
Sunshine_max=df["Sunshine"].max()

In [35]:
df["WindGustDir"].unique()

array(['W', 'WNW', 'WSW', 'NE', 'NNW', 'N', 'NNE', 'SW', nan, 'ENE',
       'SSE', 'S', 'NW', 'SE', 'ESE', 'E', 'SSW'], dtype=object)

In [36]:
WindGustSpeed_min=df["WindGustSpeed"].min()
WindGustSpeed_max=df["WindGustSpeed"].max()

In [39]:
df["WindDir9am"].unique()

array(['W', 'NNW', 'SE', 'ENE', 'SW', 'SSE', 'S', 'NE', nan, 'SSW', 'N',
       'WSW', 'ESE', 'E', 'NW', 'WNW', 'NNE'], dtype=object)

In [40]:
df["WindDir3pm"].unique()


array(['WNW', 'WSW', 'E', 'NW', 'W', 'SSE', 'ESE', 'ENE', 'NNW', 'SSW',
       'SW', 'SE', 'N', 'S', 'NNE', nan, 'NE'], dtype=object)

In [41]:
WindSpeed9am_min=df["WindSpeed9am"].min()
WindSpeed9am_max=df["WindSpeed9am"].max()

In [42]:
WindSpeed3pm_min=df["WindSpeed3pm"].min()
WindSpeed3pm_max=df["WindSpeed3pm"].max()

In [43]:
Humidity9am_min=df["Humidity9am"].min()
Humidity9am_max=df["Humidity9am"].max()

In [44]:
Humidity3pm_min=df["Humidity3pm"].min()
Humidity3pm_max=df["Humidity3pm"].max()

In [45]:
Pressure9am_min=df["Pressure9am"].min()
Pressure9am_max=df["Pressure9am"].max()

In [46]:
Pressure3pm_min=df["Pressure3pm"].min()
Pressure3pm_max=df["Pressure3pm"].max()

In [47]:
Cloud9am_min=df["Cloud9am"].min()
Cloud9am_max=df["Cloud9am"].max()

In [48]:
Cloud3pm_min=df["Cloud3pm"].min()
Cloud3pm_max=df["Cloud3pm"].max()

In [49]:
Temp9am_min=df["Temp9am"].min()
Temp9am_max=df["Temp9am"].max()

In [50]:
Temp3pm_min=df["Temp3pm"].min()
Temp3pm_max=df["Temp3pm"].max()

In [69]:
print(f"min:{MinTemp_min},max:{MinTemp_max}")

min:-8.5,max:33.9


In [70]:
print(f"min:{MaxTemp_min},max:{MaxTemp_max}")

min:-4.8,max:48.1


In [71]:
print(f"min:{Rainfall_min},max:{Rainfall_max}")

min:0.0,max:371.0


In [72]:
print(f"min:{Evaporation_min},max:{Evaporation_max}")

min:0.0,max:145.0


In [73]:
print(f"min:{Sunshine_min},max:{Sunshine_max}")

min:0.0,max:14.5


In [74]:
print(f"min:{WindGustSpeed_min},max:{WindGustSpeed_max}")

min:6.0,max:135.0


In [75]:
print(f"min:{WindSpeed9am_min},max:{WindSpeed9am_max}")

min:0.0,max:130.0


In [76]:
print(f"min:{WindSpeed3pm_min},max:{WindSpeed3pm_max}")

min:0.0,max:87.0


In [77]:
print(f"min:{Humidity9am_min},max:{Humidity9am_max}")

min:0.0,max:100.0


In [78]:
print(f"min:{Humidity3pm_min},max:{Humidity3pm_max}")

min:0.0,max:100.0


In [79]:
print(f"min:{Pressure9am_min},max:{Pressure9am_max}")

min:980.5,max:1041.0


In [80]:
print(f"min:{Pressure3pm_min},max:{Pressure3pm_max}")

min:977.1,max:1039.6


In [81]:
print(f"min:{Cloud9am_min},max:{Cloud9am_max}")

min:0.0,max:9.0


In [82]:
print(f"min:{Cloud3pm_min},max:{Cloud3pm_max}")

min:0.0,max:9.0


In [83]:
print(f"min:{Temp9am_min},max:{Temp9am_max}")

min:-7.2,max:40.2


In [84]:
print(f"min:{Temp3pm_min},max:{Temp3pm_max}")

min:-5.4,max:46.7
